# Generated by Django 4.1.7 on 2023-05-06 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[(1, 'USER'), (2, 'EDITOR'), (3, 'MODERATOR'), (4, 'ADMIN')], default=1, max_length=10),
        ),
    ]
