# Generated by Django 4.1.7 on 2023-05-06 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_alter_post_managers_tag_color_alter_post_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='excerpt',
            field=django_quill.fields.QuillField(blank=True, max_length=175, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
