# Generated by Django 4.1.7 on 2023-04-18 05:02

import apps.blog.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_tag_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'publicación', 'verbose_name_plural': 'publicaciones'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'etiqueta', 'verbose_name_plural': 'etiquetas'},
        ),
        migrations.AlterField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, storage=apps.blog.storage.ImageKitStorage, upload_to='posts', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'gif'])]),
        ),
    ]
