# Generated by Django 4.1.7 on 2023-05-09 13:31

import apps.blog.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_tag_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, max_length=200, null=True, storage=apps.blog.storage.ImageKitStorage, upload_to='tags'),
        ),
    ]
