# Generated by Django 4.1.7 on 2023-05-06 12:09

from django.db import migrations
import django_editorjs_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_excerpt_alter_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body_editorjs_custom',
            field=django_editorjs_fields.fields.EditorJsJSONField(blank=True, null=True),
        ),
    ]
