# Generated by Django 4.1.7 on 2023-05-06 12:13

from django.db import migrations
import django_editorjs_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_body_editorjs_custom'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body',
            field=django_editorjs_fields.fields.EditorJsTextField(blank=True, null=True),
        ),
    ]
