# Generated by Django 4.1.7 on 2023-05-06 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body_editorjs_custom',
        ),
    ]
