# Generated by Django 4.1.7 on 2023-05-06 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body',
        ),
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='excerpt',
        ),
    ]
